src/Lykke.Service.BcnExploler.Web/Models/Offchain/OffchainChannelViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Lykke.Service.BcnExploler.Core.Asset.Definitions;
using Lykke.Service.BcnExploler.Core.OffchainNotifcations;
using Lykke.Service.BcnExploler.Web.Models.Asset;

namespace Lykke.Service.BcnExploler.Web.Models.Offchain
{
    public class OffchainGroupViewModel
    {
        protected OffchainGroupViewModel(IGroup group, IReadOnlyDictionary<string, IAssetDefinition> assetDictionary)
        {
            AssetViewModel asset;
            if (group.IsColored)
            {
                asset = assetDictionary.ContainsKey(group.AssetId) ?
                    AssetViewModel.Create(assetDictionary[group.AssetId]) :
                    AssetViewModel.CreateNotFoundAsset(group.AssetId);
            }
            else
            {
                asset = AssetViewModel.BtcAsset.Value;
            }

            var offchainTransactions =group.Transactions.Where(p=>p.OffchainTransactionData!=null).Select(p=> OffchainTransactionViewModel.Create(p.OffchainTransactionData));
            
            this.OffChainTransactions = offchainTransactions;
            this.Asset = asset;
        }

        public AssetViewModel Asset { get; set; }

        public IEnumerable<OffchainTransactionViewModel> OffChainTransactions { get; set; }

        public static OffchainGroupViewModel Create(IGroup group, IReadOnlyDictionary<string, IAssetDefinition> assetDictionary)
        {
            return new OffchainGroupViewModel(group, assetDictionary);
        }
    }

    public class OffchainTransactionViewModel
    {
        public string TransactionId { get;  set; }

        public DateTime DateTime { get;  set; }

        public string HubAddress { get;  set; }

        public string Address1 { get;  set; }

        public string Address2 { get;  set; }

        public string AssetId { get;  set; }

        public bool IsColored { get;  set; }

        public decimal Address1Quantity { get;  set; }
        public decimal Address1QuantityDiff { get; set; }
        

        public decimal Address1QuanrtityPercents => Math.Round((Address1Quantity / TotalQuantity) * 100);
        public decimal Address2Quantity { get;  set; }
        public decimal Address2QuantityDiff { get; set; }
        public decimal Address2QuanrtityPercents => Math.Round((Address2Quantity / TotalQuantity) * 100);

        public decimal TotalQuantity => Address1Quantity + Address2Quantity;

        public static OffchainTransactionViewModel Create(IOffchainTransaction source)
        {
            return new OffchainTransactionViewModel
            {
                AssetId = source.AssetId,
                Address1 = source.Address1,
                IsColored = source.IsColored,
                DateTime = source.DateTime,
                HubAddress = source.HubAddress,
                Address1Quantity = source.Address1Quantity,
                Address2 = source.Address2,
                Address2Quantity = source.Address2Quantity,
                TransactionId = source.TransactionId,
                Address1QuantityDiff = source.Address1QuantityDiff,
                Address2QuantityDiff = source.Address2QuantityDiff
            };
        }
        
    }
}

src/Lykke.Service.BcnExploler.Web/Models/Offchain/OffchainInOutViewModel.cs
using Lykke.Service.BcnExploler.Web.Models.Asset;

namespace Lykke.Service.BcnExploler.Web.Models.Offchain
{
    public class OffchainInOutViewModel
    {
        public string Address { get; set; }

        public decimal Quantity { get; set; }

        public decimal QuantityDiff { get; set; }

        public AssetViewModel Asset { get; set; }

        public static OffchainInOutViewModel Create(string address, decimal quantity, decimal quantityDiff, AssetViewModel asset)
        {
            return new OffchainInOutViewModel
            {
                Address = address,
                Quantity = quantity,
                QuantityDiff = quantityDiff,
                Asset = asset
            };
        }
    }
}

src/Lykke.Service.BcnExploler.Web/Controllers/AddressController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Lykke.Service.BcnExploler.Core.Address;
using Lykke.Service.BcnExploler.Core.Asset;
using Lykke.Service.BcnExploler.Core.Block;
using Lykke.Service.BcnExploler.Core.MainChain;
using Lykke.Service.BcnExploler.Core.OffchainNotifcations;
using Lykke.Service.BcnExploler.Services.Helpers;
using Lykke.Service.BcnExploler.Web.Models.Address;
using Lykke.Service.BcnExploler.Web.Models.Offchain;
using Microsoft.AspNetCore.Mvc;

namespace Lykke.Service.BcnExploler.Web.Controllers
{
    public class AddressController:Controller
    {
        private readonly IAddressService _addressProvider;
        private readonly IAssetService _assetService;
        private readonly IBlockService _blockService;
        private readonly ICachedAddressService _cachedAddressService;
        private readonly ICachedMainChainService _mainChainService;
        private readonly IOffchainNotificationsService _offchainNotificationsService;

        private const int MaxOffchainPopoverChannels = 10;

        public AddressController(IAddressService addressProvider, 
            IAssetService assetService, 
            IBlockService blockService,
            ICachedMainChainService mainChainService, 
            ICachedAddressService cachedAddressService, 
            IOffchainNotificationsService offchainNotificationsService)
        {
            _addressProvider = addressProvider;
            _assetService = assetService;
            _blockService = blockService;
            _mainChainService = mainChainService;
            _cachedAddressService = cachedAddressService;
            _offchainNotificationsService = offchainNotificationsService;
        }
        
        [Route("address/{id}")]
        public async Task<ActionResult> Index(string id)
        {
            var mainInfo = _addressProvider.GetMainInfoAsync(id);
            var isOffchainHub = _offchainNotificationsService.IsHubAsync(id);

            await Task.WhenAll(mainInfo, isOffchainHub);

            if (mainInfo.Result != null)
            {
                return View(AddressMainInfoViewModel.Create(mainInfo.Result, isOffchainHub.Result));
            }

            return View("NotFound");
        }

        [Route("address/balance/{id}")]
        public Task<ActionResult> Balance(string id)
        {
            return BalanceAtBlockInner(id, null);
        }

        [Route("address/balance/{id}/block")]
        public Task<ActionResult> BalanceAtBlock(string id, [FromQuery] int? at)
        {
            return BalanceAtBlockInner(id, at);
        }

        private async Task<ActionResult> BalanceAtBlockInner(string id, int? at)
        {
            var balance = _addressProvider.GetBalanceAsync(id, at);
            var assetDefinitionDictionary = _assetService.GetAssetDefinitionDictionaryAsync();
            var lastBlock = _blockService.GetLastBlockHeaderAsync();
            var offchainBlocks = _offchainNotificationsService.GetGroups(address: id, openOnly: true,
                take: MaxOffchainPopoverChannels, offchainOnly: true);
            var isOffchainHub = _offchainNotificationsService.IsHubAsync(id);
            Task<IBlockHeader> atBlockTask;
            if (at != null)
            {
                atBlockTask = _blockService.GetBlockHeaderAsync(at.ToString());
            }
            else
            {
                atBlockTask = Task.FromResult<IBlockHeader>(null);
            }

            await Task.WhenAll(balance, assetDefinitionDictionary, lastBlock, atBlockTask, offchainBlocks, isOffchainHub);

            if (balance.Result != null)
            {
                return View("Balance" ,AddressBalanceViewModel.Create(balance.Result,
                    assetDefinitionDictionary.Result,
                    lastBlock.Result,
                    atBlockTask.Result,
                    offchainBlocks.Result,
                    isOffchainHub.Result));
            }

            if (at != null && atBlockTask.Result == null)
            {
                return RedirectToAction("BalanceAtBlock", new {id = id, at = lastBlock.Result});
            }

            return NotFound();
        }

        [Route("address/balance/{id}/time/")]
        public async Task<ActionResult> BalanceAtTime([FromQuery]DateTime at, string id)
        {
            var mainChain = await _mainChainService.GetMainChainAsync();

            var block = mainChain.GetClosestToTimeBlock(at);

            return RedirectToAction("BalanceAtBlock", new { id = id, at = block?.Height ?? 0 });
        }

        
        [Route("address/transactions/{id}")]
        public async Task<ActionResult> Transactions(string id)
        {
            var onchainTransactions = _cachedAddressService.GetTransactions(id);
            var offchainTransactionCount = _offchainNotificationsService.GetTransactionCountByAddressAsync(id);

            await Task.WhenAll(onchainTransactions, offchainTransactionCount);

            return View(AddressTransactionsViewModel.Create(id, onchainTransactions.Result, offchainTransactionCount.Result));
        }

        [Route("address/offchaintransactionspage")]
        public async Task<ActionResult> OffchainMixedTransactionsPage(string address, int page, int pageSize)
        {
            var getTransactions =
                _offchainNotificationsService.GetMixedTransactionsByAddressAsync(address,
                    PageOptions.Create(page, pageSize));
            var getAssetDictionary = _assetService.GetAssetDefinitionDictionaryAsync();

            await Task.WhenAll(getTransactions, getAssetDictionary);

            return View("Offchain/OffchainMixedTransactionsPage", getTransactions.Result.Select(p => OffchainMixedTransactionViewModel.Create(p, getAssetDictionary.Result)));
        }
    }
}

src/Lykke.Service.BcnExploler.Web/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BCNExplorer.Web.Models;
using Lykke.Service.BcnExploler.Core.Asset;
using Lykke.Service.BcnExploler.Core.AssetBalanceChanges;
using Lykke.Service.BcnExploler.Core.Block;
using Lykke.Service.BcnExploler.Core.MainChain;
using Lykke.Service.BcnExploler.Services.Helpers;
using Lykke.Service.BcnExploler.Web.Models.Asset;
using Microsoft.AspNetCore.Mvc;

namespace Lykke.Service.BcnExploler.Web.Controllers
{
    public class AssetController : Controller
    {
        private readonly IAssetService _assetService;
        private readonly IBlockService _blockService;
        private readonly IAssetBalanceChangesRepository _balanceChangesRepository;

        private readonly ICachedMainChainService _mainChainService;

        public AssetController(IAssetService assetService,
            IBlockService blockService,
            ICachedMainChainService mainChainService, 
            IAssetBalanceChangesRepository assetBalanceChangesRepository)
        {
            _assetService = assetService;
            _blockService = blockService;
            _mainChainService = mainChainService;
            _balanceChangesRepository = assetBalanceChangesRepository;
        }

        [Route("asset/{id}")]
        public async Task<ActionResult> Index(string id)
        {
            var result = await _assetService.GetAssetAsync(id);
            if (result != null)
            {
                return View(AssetViewModel.Create(result));
            }

            return View("NotFound");
        }

        [Route("assets")]
        public ActionResult AssetDirectiory()
        {
            return View();
        }

        #region owners

        [ResponseCache(Duration = 60, Location = ResponseCacheLocation.Any)]
        [Route("asset/owners/{id}")]
        public Task<ActionResult> Owners(string id)
        {
            return _OwnersInner(id);
        }

        [Route("asset/ownershistory/{id}")]
        public Task<ActionResult> OwnersHistory(string id, [FromQuery]int? at)
        {
            return _OwnersInner(id, at);
        }

        [Route("asset/ownershistorybydata/{id}")]
        public async Task<ActionResult> OwnersHistoryByDate([FromQuery]DateTime at, string id)
        {
            var mainChain = await _mainChainService.GetMainChainAsync();

            var block = mainChain.GetClosestToTimeBlock(at);

            return RedirectToAction("OwnersHistory", new { id = id, at = block?.Height ?? 0 });
        }

        private async Task<ActionResult> _OwnersInner(string id, int? at = null)
        {
            var result = await GetOwnersAsync(id, at);

            if (result != null)
            {
                return View("Owners", result);
            }

            return View("NotFound");
        }

        private async Task<AssetCoinholdersViewModel> GetOwnersAsync(string id, int? at)
        {
            var asset = await _assetService.GetAssetAsync(id);

            if (asset != null)
            {
                var summaryTask = _balanceChangesRepository.GetSummaryAsync(at, asset.AssetIds.ToArray());
                var addressChangesTask = _balanceChangesRepository.GetBlocksWithChanges(asset.AssetIds);
                var lastBlockTask = _blockService.GetLastBlockHeaderAsync();
                Task<IDictionary<string, double>> addressChangesAtBlockTask;
                Task<IBlockHeader> atBlockInfoTask;
                if (at != null)
                {
                    atBlockInfoTask = _blockService.GetBlockHeaderAsync(at.ToString());
                    addressChangesAtBlockTask = _balanceChangesRepository.GetAddressQuantityChangesAtBlock(at.Value, asset.AssetIds.ToArray());
                }
                else
                {
                    atBlockInfoTask = Task.FromResult((IBlockHeader)null);
                    addressChangesAtBlockTask = Task.FromResult((IDictionary<string, double>)new Dictionary<string, double>());
                }

                await Task.WhenAll(addressChangesAtBlockTask, summaryTask, addressChangesTask, lastBlockTask, atBlockInfoTask);

                var result = AssetCoinholdersViewModel.Create(
                    AssetViewModel.Create(asset),
                    summaryTask.Result,
                    at,
                    addressChangesAtBlockTask.Result,
                    addressChangesTask.Result,
                    lastBlockTask.Result,
                    atBlockInfoTask.Result
                    );

                return result;
            }

            return null;
        }

        [Route("asset/transactions/{id}")]
        public async Task<ActionResult> Transactions(string id)
        {
            var asset = await _assetService.GetAssetAsync(id);

            if (asset != null)
            {
                var txs = await _balanceChangesRepository.GetTransactionsAsync(asset.AssetIds);

                var txList = new TransactionIdList(txs.Select(p => p.Hash));

                return View("~/Views/Transaction/TransactionIdList.cshtml", txList);
            }


            return View("NotFound");
        }

        [Route("asset/ownerstocsv/{id}")]
        public async Task<ActionResult> OwnersToCsv(string id, [FromQuery]int at)
        {
            var result = await GetOwnersAsync(id, at);

            if (result != null)
            {
                return File(await result.ToCsvAsync(), "text/csv", $"Coinholders-{result.Asset.NameShort}-{at}.csv");
            }

            return View("NotFound");
        }

        #endregion
    }
}

src/Lykke.Service.BcnExploler.Web/Controllers/OffchainTransactionController.cs
using System;
using System.Threading.Tasks;
using Lykke.Service.BcnExploler.Core.Asset;
using Lykke.Service.BcnExploler.Core.OffchainNotifcations;
using Lykke.Service.BcnExploler.Core.Transaction;
using Lykke.Service.BcnExploler.Web.Models.Offchain;
using Microsoft.AspNetCore.Mvc;

namespace Lykke.Service.BcnExploler.Web.Controllers
{
    public class OffchainTransactionController: Controller
    {
        private readonly IAssetService _assetService;
        private readonly IOffchainNotificationsService _offchainNotificationsService;

        public OffchainTransactionController(ICachedTransactionService transactionService,
            IAssetService assetService,
            IOffchainNotificationsService offchainNotificationsService)
        {
            _assetService = assetService;
            _offchainNotificationsService = offchainNotificationsService;
        }

        [Route("transaction/offchain/{id}")]
        public async Task<ActionResult> Index(string id)
        {
            var getOffchainTx = _offchainNotificationsService.GetOffchainMixedTransaction(id);
            var getAssetDictionary = _assetService.GetAssetDefinitionDictionaryAsync();

            await Task.WhenAll(getOffchainTx, getAssetDictionary);


            if (getOffchainTx.Result == null)
            {
                return View("NotFound");
            }
            

            var offchainTransactionCount =  await _offchainNotificationsService.GetTransactionCountByGroupAsync(getOffchainTx.Result.GroupId);

            return View(OffchainTransactionDetailsViewModel.Create(getOffchainTx.Result, 
                getAssetDictionary.Result,
                offchainTransactionCount));
        }
    }
}

src/Lykke.Service.BcnExploler.Web/Views/Shared/Offchain/OffchainChannelPagedList.cshtml
@using Lykke.Service.BcnExploler.Web.Models.Offchain
@model OffchainChannelPagedList 
@{
    Layout = null;
}

<div class="section section--heading">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h3>
                    Channels 
                    <span class="js-offchain-loaded-channel-count">0</span>
                    <span>
                        of @Model.ChannelCount
                    </span>
                </h3>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<ul>
    @foreach (var pageMeta in Model.Pages)
    {
        <li class="js-offchain-page hidden" data-page="@pageMeta.PageNumber"
            data-load-url="@Model.BuildUrl(Url, pageMeta.PageNumber)">


            <div class="show_more">
                <a class="btn js-load-offchain-page">Show More</a>
            </div>
        </li>
    }
</ul>


@Html.Loader(htmlId: "js-offchain-page-loader", htmlClass: "hidden")

src/Lykke.Service.BcnExploler.Web/Views/Shared/Offchain/OffchainClientPopover.cshtml
@using Lykke.Service.BcnExploler.Services.Helpers
@using Lykke.Service.BcnExploler.Web.Models.Offchain
@model OffchainClientPopoverViewModel

<div class="popover_control multisig_popover">
    <a class="js-offchain-balance-popover" tabindex="0" role="button" data-toggle="popover" data-placement="bottom" data-original-title="" title="">
        @Model.Title
    </a>
    <div class="popover-content">


        @foreach (var group in Model.Groups)
        {
            var confirmedTx = group.Transactions.First();

            <h3>Off-chain channels</h3>

            <table class="issuer">
                <tbody>
                <tr>
                    <td class="issuer__content">

                        <div class="issuer__name">
                            @confirmedTx.AddressQuantity.ToStringBtcFormat() @group.Asset.NameShort
                        </div>
                        <div class="links_group text-muted">
                            <a href="@Url.Action("Index", "Address", new {id = confirmedTx.HubAddress})">
                                <span class="truncate" title="@confirmedTx.HubAddress">@confirmedTx.HubAddress</span>
                            </a>
                        </div>
                    </td>
                    <td class="issuer__content text-right">
                        <div class="graph graph--multisig">
                            @foreach (var tx in group.Transactions.OrderBy(p => p.DateTime))
                            {
                                <div class="graph_candle">
                                    <span style="height: @tx.AddressQuanrtityPercents%"></span>
                                </div>
                            }
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>

        }

    </div>
</div>

src/Lykke.Service.BcnExploler.Web/Views/Shared/Offchain/OffchainHubPopover.cshtml
@using Lykke.Service.BcnExploler.Services.Helpers
@using Lykke.Service.BcnExploler.Web.Models.Offchain
@model OffchainHubPopoverViewModel

<div class="popover_control multisig_popover">
    <a class="js-offchain-balance-popover" tabindex="0" role="button" data-toggle="popover" data-placement="bottom" data-original-title="" title="">
        @Model.Title
    </a>
    <div class="popover-content">


        @foreach (var group in Model.Groups)
        {
            var confirmedTx = group.OffChainTransactions.First();

            <h3>Multisig key holders</h3>

            <table class="issuer">
                <tbody>
                <tr>
                    <td class="issuer__content">

                        <div class="issuer__name">
                            @confirmedTx.Address1Quantity.ToStringBtcFormat() @group.Asset.NameShort
                        </div>
                        <div class="links_group text-muted">
                            <a href="@Url.Action("Index", "Address", new {id = confirmedTx.Address1})">
                                <span class="truncate" title="@confirmedTx.Address1">@confirmedTx.Address1</span>
                            </a>
                        </div>
                    </td>
                    <td class="issuer__content text-right">
                        <div class="graph graph--multisig">
                            @foreach (var tx in group.OffChainTransactions.OrderBy(p => p.DateTime))
                            {
                                <div class="graph_candle">
                                    <span style="height: @tx.Address1QuanrtityPercents%"></span>
                                </div>
                            }
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>

            <table class="issuer">
                <tbody>
                <tr>
                    <td class="issuer__content">

                        <div class="issuer__name">
                            @confirmedTx.Address2Quantity.ToStringBtcFormat() @group.Asset.NameShort
                        </div>
                        <div class="links_group text-muted">
                            <a href="@Url.Action("Index", "Address", new {id = confirmedTx.Address2})">
                                <span class="truncate" title="@confirmedTx.Address2">@confirmedTx.Address2</span>
                            </a>
                        </div>
                    </td>
                    <td class="issuer__content text-right">
                        <div class="graph graph--multisig">
                            @foreach (var tx in group.OffChainTransactions.OrderBy(p => p.DateTime))
                            {
                                <div class="graph_candle">
                                    <span style="height: @tx.Address2QuanrtityPercents%"></span>
                                </div>
                            }
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        }

    </div>
</div>

src/Lykke.Service.BcnExploler.Web/Views/Shared/Offchain/OffchainInOut.cshtml
@using Lykke.Service.BcnExploler.Services.Helpers
@using Lykke.Service.BcnExploler.Web.Models.Offchain
@model Lykke.Service.BcnExploler.Web.Models.Offchain.OffchainInOutViewModel 
@{
    Layout = null;
}

<div class="transaction_list__item" data-address="@Model.Address">
    <div class="row">
        <div class="col-xs-8">
            <a href="@Url.Action("Index", "Address", new {id = Model.Address})">
                <span class="truncate" title="@Model.Address">@Model.Address</span>
            </a>
            @*<button class="btn btn--icon btn_asset_download" type="button">
                    <i class="icon icon--download"></i>
                </button>*@
        </div>
        <div class="col-xs-4">
            <span>@Model.Quantity.ToStringBtcFormat() @(Model.Asset.IsColored ? Model.Asset.NameShort: "")</span>
            @{
                var diffClass = "text--gray";
                if (Model.QuantityDiff > 0)
                {
                    diffClass = "text--green";
                }
                else if(Model.QuantityDiff<0)
                {
                    diffClass = "text--red";
                }
            }
            <span class="@diffClass">(@Model.QuantityDiff.ToStringBtcFormat())</span>
        </div>
    </div>
</div>

src/Lykke.Service.BcnExploler.Web/Views/Shared/Offchain/OffchainMixedTransactionsPage.cshtml
@using Lykke.Service.BcnExploler.Web.Models.Offchain
@model IEnumerable<OffchainMixedTransactionViewModel>
@{
    Layout = null;
}


@foreach (var item in Model)
{
    @Html.Partial("Offchain/OffchainMixedTransactionViewModel", item)
}

src/Lykke.Service.BcnExploler.Web/Views/Shared/Offchain/OffchainTransactionDetails.cshtml
@using Common
@using Lykke.Service.BcnExploler.Core.OffchainNotifcations
@using Lykke.Service.BcnExploler.Services.Helpers
@using Lykke.Service.BcnExploler.Web.Models.Asset
@using Lykke.Service.BcnExploler.Web.Models.Offchain
@model OffChainTransactionViewModel

@{
    Layout = null;
}   

<div class="panel transaction_panel js-offchain-transaction-details" >
    <div class="container">

        <div class="panel__header">
            <div class="row">
                <div class="col-xs-12 col-sm-4 pull-right text-right">
                    <div class="confirmation_label">
                        @if (Model.Type == MixedTransactionType.RevokedOffchain)
                        {
                            <span class="label label--gray">Revoked off-chain</span>
                        }
                        else if(Model.Type == MixedTransactionType.ConfirmedOffchain)
                        {
                            <span class="label label--green">Confirmed off-chain</span>
                        }
                        else if(Model.Type == MixedTransactionType.ReOpenedOffchain)
                        {
                            <span class="label label--gray">Revoked</span>
                        }
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="address_code">
                        <a href="@Url.Action("Index", "OffchainTransaction", new {id=Model.TransactionId})">@Model.TransactionId</a>
                        <button class="btn btn--icon copy_code" type="button" title="Copy code">
                            <i class="icon icon--copy"></i>
                        </button>
                    </div>
                    <span class="action_text">@Model.DateTime.ToStringBcnExplolerFormat()</span>
                    <span class="middot">·</span>
                    <span class="action_text">@Model.InputCount @Utils.GenderAmount(Model.InputCount, "input", "inputs", "inputs")</span>
                    <span class="middot">·</span>
                    <span class="action_text">@Model.OutputCount @Utils.GenderAmount(Model.OutputCount, "output", "outputs", "outputs")</span>
                </div>
            </div>
        </div>

        <div class="panel__body">
            <div class="transaction_details">
                <div class="transaction_details__header">
                    <table class="issuer">
                        <tbody>
                        <tr>
                            <td class="issuer__img">
                                    
                                @if (Model.Asset.ShowAssetDetailsLink)
                                {
                                    <a href="@Url.Action("Index", "Asset", new {id = Model.Asset.AssetIds.FirstOrDefault()})">
                                        <img src="@Model.Asset.IconUrl" width="48" alt="">
                                    </a>
                                }
                                else
                                {
                                    <img src="@Model.Asset.IconUrl" width="48" alt="">
                                }

                            </td>
                            <td class="issuer__content">
                                <div class="issuer__name pull-left">
                                    @if (Model.Asset.ShowAssetDetailsLink)
                                    {
                                        <a href="@Url.Action("Index", "Asset", new {id = Model.Asset.AssetIds.FirstOrDefault()})">
                                            @Model.Asset.Name
                                        </a>
                                    }
                                    else
                                    {
                                        @Model.Asset.Name
                                    }
                                </div>
                                <div class="wallet_value pull-right">@Model.TotalQuantity.ToStringBtcFormat() @Model.Asset.NameShort</div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <div class="transaction_details__body">
                    <div class="transaction_item">
                        <div class="transaction_item__left">
                            <div class="transaction_list">

                                <div class="transaction_list__item" data-address="@Model.HubAddress">
                                    <div class="row">
                                        <div class="col-xs-8">
                                            <div class="links_group">
                                                <a href="@Url.Action("Index", "Address", new { id = Model.HubAddress })">
                                                    <span class="truncate" title="@Model.HubAddress">@Model.HubAddress</span>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-xs-4"> - @Model.TotalQuantity.ToStringBtcFormat() @(Model.Asset.IsColored ? Model.Asset.NameShort: "")</div>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="transaction_item__center">
                            <div class="transaction_arrow"><i class="icon icon--arrow_right_circle"></i>
                            </div>
                        </div>

                        <div class="transaction_item__right">
                            <div class="transaction_list">
                                @Html.Partial("Offchain/OffchainInOut", OffchainInOutViewModel.Create(Model.Address1, Model.Address1Quantity, Model.Address1QuantityDiff, Model.Asset))
                                @Html.Partial("Offchain/OffchainInOut", OffchainInOutViewModel.Create(Model.Address2, Model.Address2Quantity, Model.Address2QuantityDiff, Model.Asset))
                            </div>
                        </div>
                    </div> 
                </div> 
            </div> 

        </div> 

    </div>
</div>