src/Lykke.Service.BcnExploler.Web/Models/Transaction/InOutsViewModel.cs
using System.Collections.Generic;

namespace Lykke.Service.BcnExploler.Web.Models.Transaction
{
    public class InOutsViewModel
    {
        public IInOutViewModel InOut { get; set; }
        public string AggregatedTransContainerId { get; set; }

        public static InOutsViewModel Create(IInOutViewModel inOutViewModel, string aggregatedTransContainerId = null)
        {
            return new InOutsViewModel
            {
                InOut = inOutViewModel,
                AggregatedTransContainerId = aggregatedTransContainerId
            };
        }
    }

    public class BtcInOutsViewModel
    {
        public IEnumerable<AggregatedInOut<AssetInOutBase>> AggregatedIns { get; set; }
        public IEnumerable<AggregatedInOut<AssetInOutBase>> AggregatedOuts { get; set; }
        public bool ShowConsumedReleased { get; set; }
        public TransactionViewModel.BitcoinAsset Bitcoin { get; set; }

        public static BtcInOutsViewModel CreateWithChange(TransactionViewModel.BitcoinAsset bitcoin,
            bool showConsumedReleased)
        {
            return new BtcInOutsViewModel
            {
                AggregatedIns = bitcoin.AggregatedIns,
                AggregatedOuts = bitcoin.AggregatedOuts,
                ShowConsumedReleased = showConsumedReleased,
                Bitcoin = bitcoin
            };
        }

        public static BtcInOutsViewModel CreateWithoutChange(TransactionViewModel.BitcoinAsset bitcoin,
            bool showConsumedReleased)
        {
            return new BtcInOutsViewModel
            {
                AggregatedIns = bitcoin.AggregatedInsWithoutChange,
                AggregatedOuts = bitcoin.AggregatedOutsWithoutChange,
                ShowConsumedReleased = showConsumedReleased,
                Bitcoin = bitcoin
            };
        }
    }

    public class ColoredAssetInOutsViewModel
    {
        public TransactionViewModel.ColoredAsset ColoredAsset { get; set; }

        public IEnumerable<AggregatedInOut<TransactionViewModel.ColoredAsset.In>> AggregatedIns { get; set; }
        public IEnumerable<AggregatedInOut<TransactionViewModel.ColoredAsset.Out>> AggregatedOuts { get; set; }

        public static ColoredAssetInOutsViewModel CreateWithChange(TransactionViewModel.ColoredAsset coloredAsset)
        {
            return new ColoredAssetInOutsViewModel
            {
                AggregatedIns = coloredAsset.AggregatedIns,
                AggregatedOuts = coloredAsset.AggregatedOuts,
                ColoredAsset = coloredAsset
            };
        }

        public static ColoredAssetInOutsViewModel CreateWithoutChange(TransactionViewModel.ColoredAsset coloredAsset)
        {
            return new ColoredAssetInOutsViewModel
            {
                AggregatedIns = coloredAsset.AggregatedInsWithoutChange,
                AggregatedOuts = coloredAsset.AggregatedOutsWithoutChange,
                ColoredAsset = coloredAsset
            };
        }
    }
}

src/Lykke.Service.BcnExploler.Web/Controllers/AddressController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Lykke.Service.BcnExploler.Core.Address;
using Lykke.Service.BcnExploler.Core.Asset;
using Lykke.Service.BcnExploler.Core.Block;
using Lykke.Service.BcnExploler.Core.MainChain;
using Lykke.Service.BcnExploler.Core.OffchainNotifcations;
using Lykke.Service.BcnExploler.Services.Helpers;
using Lykke.Service.BcnExploler.Web.Models.Address;
using Lykke.Service.BcnExploler.Web.Models.Offchain;
using Microsoft.AspNetCore.Mvc;

namespace Lykke.Service.BcnExploler.Web.Controllers
{
    public class AddressController:Controller
    {
        private readonly IAddressService _addressProvider;
        private readonly IAssetService _assetService;
        private readonly IBlockService _blockService;
        private readonly ICachedAddressService _cachedAddressService;
        private readonly ICachedMainChainService _mainChainService;
        private readonly IOffchainNotificationsService _offchainNotificationsService;

        private const int MaxOffchainPopoverChannels = 10;

        public AddressController(IAddressService addressProvider, 
            IAssetService assetService, 
            IBlockService blockService,
            ICachedMainChainService mainChainService, 
            ICachedAddressService cachedAddressService, 
            IOffchainNotificationsService offchainNotificationsService)
        {
            _addressProvider = addressProvider;
            _assetService = assetService;
            _blockService = blockService;
            _mainChainService = mainChainService;
            _cachedAddressService = cachedAddressService;
            _offchainNotificationsService = offchainNotificationsService;
        }
        
        [Route("address/{id}")]
        public async Task<ActionResult> Index(string id)
        {
            var mainInfo = _addressProvider.GetMainInfoAsync(id);
            var isOffchainHub = _offchainNotificationsService.IsHubAsync(id);

            await Task.WhenAll(mainInfo, isOffchainHub);

            if (mainInfo.Result != null)
            {
                return View(AddressMainInfoViewModel.Create(mainInfo.Result, isOffchainHub.Result));
            }

            return View("NotFound");
        }

        [Route("address/balance/{id}")]
        public Task<ActionResult> Balance(string id)
        {
            return BalanceAtBlockInner(id, null);
        }

        [Route("address/balance/{id}/block")]
        public Task<ActionResult> BalanceAtBlock(string id, [FromQuery] int? at)
        {
            return BalanceAtBlockInner(id, at);
        }

        private async Task<ActionResult> BalanceAtBlockInner(string id, int? at)
        {
            var balance = _addressProvider.GetBalanceAsync(id, at);
            var assetDefinitionDictionary = _assetService.GetAssetDefinitionDictionaryAsync();
            var lastBlock = _blockService.GetLastBlockHeaderAsync();
            var offchainBlocks = _offchainNotificationsService.GetGroups(address: id, openOnly: true,
                take: MaxOffchainPopoverChannels, offchainOnly: true);
            var isOffchainHub = _offchainNotificationsService.IsHubAsync(id);
            Task<IBlockHeader> atBlockTask;
            if (at != null)
            {
                atBlockTask = _blockService.GetBlockHeaderAsync(at.ToString());
            }
            else
            {
                atBlockTask = Task.FromResult<IBlockHeader>(null);
            }

            await Task.WhenAll(balance, assetDefinitionDictionary, lastBlock, atBlockTask, offchainBlocks, isOffchainHub);

            if (balance.Result != null)
            {
                return View("Balance" ,AddressBalanceViewModel.Create(balance.Result,
                    assetDefinitionDictionary.Result,
                    lastBlock.Result,
                    atBlockTask.Result,
                    offchainBlocks.Result,
                    isOffchainHub.Result));
            }

            if (at != null && atBlockTask.Result == null)
            {
                return RedirectToAction("BalanceAtBlock", new {id = id, at = lastBlock.Result});
            }

            return NotFound();
        }

        [Route("address/balance/{id}/time/")]
        public async Task<ActionResult> BalanceAtTime([FromQuery]DateTime at, string id)
        {
            var mainChain = await _mainChainService.GetMainChainAsync();

            var block = mainChain.GetClosestToTimeBlock(at);

            return RedirectToAction("BalanceAtBlock", new { id = id, at = block?.Height ?? 0 });
        }

        
        [Route("address/transactions/{id}")]
        public async Task<ActionResult> Transactions(string id)
        {
            var onchainTransactions = _cachedAddressService.GetTransactions(id);
            var offchainTransactionCount = _offchainNotificationsService.GetTransactionCountByAddressAsync(id);

            await Task.WhenAll(onchainTransactions, offchainTransactionCount);

            return View(AddressTransactionsViewModel.Create(id, onchainTransactions.Result, offchainTransactionCount.Result));
        }

        [Route("address/offchaintransactionspage")]
        public async Task<ActionResult> OffchainMixedTransactionsPage(string address, int page, int pageSize)
        {
            var getTransactions =
                _offchainNotificationsService.GetMixedTransactionsByAddressAsync(address,
                    PageOptions.Create(page, pageSize));
            var getAssetDictionary = _assetService.GetAssetDefinitionDictionaryAsync();

            await Task.WhenAll(getTransactions, getAssetDictionary);

            return View("Offchain/OffchainMixedTransactionsPage", getTransactions.Result.Select(p => OffchainMixedTransactionViewModel.Create(p, getAssetDictionary.Result)));
        }
    }
}

src/Lykke.Service.BcnExploler.Web/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BCNExplorer.Web.Models;
using Lykke.Service.BcnExploler.Core.Asset;
using Lykke.Service.BcnExploler.Core.AssetBalanceChanges;
using Lykke.Service.BcnExploler.Core.Block;
using Lykke.Service.BcnExploler.Core.MainChain;
using Lykke.Service.BcnExploler.Services.Helpers;
using Lykke.Service.BcnExploler.Web.Models.Asset;
using Microsoft.AspNetCore.Mvc;

namespace Lykke.Service.BcnExploler.Web.Controllers
{
    public class AssetController : Controller
    {
        private readonly IAssetService _assetService;
        private readonly IBlockService _blockService;
        private readonly IAssetBalanceChangesRepository _balanceChangesRepository;

        private readonly ICachedMainChainService _mainChainService;

        public AssetController(IAssetService assetService,
            IBlockService blockService,
            ICachedMainChainService mainChainService, 
            IAssetBalanceChangesRepository assetBalanceChangesRepository)
        {
            _assetService = assetService;
            _blockService = blockService;
            _mainChainService = mainChainService;
            _balanceChangesRepository = assetBalanceChangesRepository;
        }

        [Route("asset/{id}")]
        public async Task<ActionResult> Index(string id)
        {
            var result = await _assetService.GetAssetAsync(id);
            if (result != null)
            {
                return View(AssetViewModel.Create(result));
            }

            return View("NotFound");
        }

        [Route("assets")]
        public ActionResult AssetDirectiory()
        {
            return View();
        }

        #region owners

        [ResponseCache(Duration = 60, Location = ResponseCacheLocation.Any)]
        [Route("asset/owners/{id}")]
        public Task<ActionResult> Owners(string id)
        {
            return _OwnersInner(id);
        }

        [Route("asset/ownershistory/{id}")]
        public Task<ActionResult> OwnersHistory(string id, [FromQuery]int? at)
        {
            return _OwnersInner(id, at);
        }

        [Route("asset/ownershistorybydata/{id}")]
        public async Task<ActionResult> OwnersHistoryByDate([FromQuery]DateTime at, string id)
        {
            var mainChain = await _mainChainService.GetMainChainAsync();

            var block = mainChain.GetClosestToTimeBlock(at);

            return RedirectToAction("OwnersHistory", new { id = id, at = block?.Height ?? 0 });
        }

        private async Task<ActionResult> _OwnersInner(string id, int? at = null)
        {
            var result = await GetOwnersAsync(id, at);

            if (result != null)
            {
                return View("Owners", result);
            }

            return View("NotFound");
        }

        private async Task<AssetCoinholdersViewModel> GetOwnersAsync(string id, int? at)
        {
            var asset = await _assetService.GetAssetAsync(id);

            if (asset != null)
            {
                var summaryTask = _balanceChangesRepository.GetSummaryAsync(at, asset.AssetIds.ToArray());
                var addressChangesTask = _balanceChangesRepository.GetBlocksWithChanges(asset.AssetIds);
                var lastBlockTask = _blockService.GetLastBlockHeaderAsync();
                Task<IDictionary<string, double>> addressChangesAtBlockTask;
                Task<IBlockHeader> atBlockInfoTask;
                if (at != null)
                {
                    atBlockInfoTask = _blockService.GetBlockHeaderAsync(at.ToString());
                    addressChangesAtBlockTask = _balanceChangesRepository.GetAddressQuantityChangesAtBlock(at.Value, asset.AssetIds.ToArray());
                }
                else
                {
                    atBlockInfoTask = Task.FromResult((IBlockHeader)null);
                    addressChangesAtBlockTask = Task.FromResult((IDictionary<string, double>)new Dictionary<string, double>());
                }

                await Task.WhenAll(addressChangesAtBlockTask, summaryTask, addressChangesTask, lastBlockTask, atBlockInfoTask);

                var result = AssetCoinholdersViewModel.Create(
                    AssetViewModel.Create(asset),
                    summaryTask.Result,
                    at,
                    addressChangesAtBlockTask.Result,
                    addressChangesTask.Result,
                    lastBlockTask.Result,
                    atBlockInfoTask.Result
                    );

                return result;
            }

            return null;
        }

        [Route("asset/transactions/{id}")]
        public async Task<ActionResult> Transactions(string id)
        {
            var asset = await _assetService.GetAssetAsync(id);

            if (asset != null)
            {
                var txs = await _balanceChangesRepository.GetTransactionsAsync(asset.AssetIds);

                var txList = new TransactionIdList(txs.Select(p => p.Hash));

                return View("~/Views/Transaction/TransactionIdList.cshtml", txList);
            }


            return View("NotFound");
        }

        [Route("asset/ownerstocsv/{id}")]
        public async Task<ActionResult> OwnersToCsv(string id, [FromQuery]int at)
        {
            var result = await GetOwnersAsync(id, at);

            if (result != null)
            {
                return File(await result.ToCsvAsync(), "text/csv", $"Coinholders-{result.Asset.NameShort}-{at}.csv");
            }

            return View("NotFound");
        }

        #endregion
    }
}

src/Lykke.Service.BcnExploler.Web/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BCNExplorer.Web.Models;
using Common;
using Core.Transaction;
using Lykke.Service.BcnExploler.Core.Asset;
using Lykke.Service.BcnExploler.Core.Transaction;
using Lykke.Service.BcnExploler.Web.Models.Transaction;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Lykke.Service.BcnExploler.Web.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly IAssetService _assetService;
        private readonly ICachedTransactionService _cachedTransactionService;

        public TransactionController(ITransactionService transactionService, IAssetService assetService, ICachedTransactionService cachedTransactionService)
        {
            _transactionService = transactionService;
            _assetService = assetService;
            _cachedTransactionService = cachedTransactionService;
        }

        [Route("transaction/{id}")]
        public async Task<ActionResult> Index(string id)
        {
            var ninjaTransaction = await _transactionService.GetAsync(id);

            if (ninjaTransaction != null)
            {
                var result = TransactionViewModel.Create(ninjaTransaction, await _assetService.GetAssetDefinitionDictionaryAsync());
 
                return View(result);
            }

            return View("NotFound");
        }

        [Route("transation/list")]
        public async Task<ActionResult> List(IList<string> ids)
        {
            var assetDictionary = _assetService.GetAssetDefinitionDictionaryAsync();

            var loadTransactionTask = _cachedTransactionService.GetAsync(ids); 

            await Task.WhenAll(loadTransactionTask, assetDictionary);

            var mappedTxs = await loadTransactionTask.Result.SelectAsync(p =>
                Task.Run(() => TransactionViewModel.Create(p, assetDictionary.Result)));

            return View(mappedTxs.ToList().OrderBy(p => ids.IndexOf(p.TransactionId)));
        }
    }
}

src/Lykke.Service.BcnExploler.Web/Views/Shared/TransactionDetails/InOut.cshtml
@model Lykke.Service.BcnExploler.Web.Models.Transaction.InOutsViewModel
<div class="transaction_list__item" data-address="@Model.InOut.Address">
    <div class="row">
        <div class="col-xs-8">
            <div class="links_group">
                @if (Model.InOut.ShowPreviousTransaction)
                    {
                    <a href="@Url.Action("Index", "Transaction", new {id = Model.InOut.PreviousTransactionId})" class="btn btn--icon transaction_prev_link"><i class="icon icon--prev_transaction"></i></a>
                    }

                @if (Model.InOut.IsUnrecoginzedAddress)
                    {
                    <span>Unrecognized address</span>
                    }
                    else
                    {
                    <a href="@Url.Action("Index", "Address", new {id = Model.InOut.Address})" class="transaction_current_link">
                        @Html.Truncate(Model.InOut.Address)
                    </a>
                    }

            </div>
        </div>
        <div class="col-xs-4">

            @if (Model.InOut.ShowAggregatedTransactions)
                {

                <a href="#@Model.AggregatedTransContainerId" class="open_hidden_content _word_break">
                    @Model.InOut.ValueDescription
                    <span class="_no_break">
                        @Model.InOut.AssetDescription
                        (@Model.InOut.AggregatedTransactionCount)

                    </span>
                    <i class="icon icon--chevron-thin-down"></i>
                </a>
                }
                else
                {
                <text>
                @Model.InOut.ValueDescription
                <span class="_no_break">
                    @Model.InOut.AssetDescription
                </span>
                </text>
                }
            @if (Model.InOut.HasColoredEquivalent)
                {
                <div class="btn_colored_coin js-tranasction-popover" data-toggle="popover" data-placement="top"
                     data-content="@Model.InOut.ColoredEquivalentDescription colored">
                    <span class="btn_colored_coin__icon"></span>
                </div>
                }
        </div>
    </div>
</div>

src/Lykke.Service.BcnExploler.Web/Views/Shared/TransactionDetails/TransactionDetails.cshtml
@using Common
@using Lykke.Service.BcnExploler.Services.Helpers
@using Lykke.Service.BcnExploler.Web.Models.Transaction
@model TransactionViewModel
@{
    Layout = null;
    var toggleChangeContainer = "js-toggle-changes-container-" + Guid.NewGuid().ToString("N");
    var toggleChangeItemClass = "js-toggle-change-item";
}

@if (Model != null)
{
    <div class="panel transaction_panel js-transaction-details @toggleChangeContainer" >
        <div class="container">
            <div class="panel__header">
                <div class="row">
                    <div class="col-xs-12 col-sm-3 pull-right text-right">
                        @{
                            var confirmationsClass = Model.Block?.Confirmations >= 5 ? "label--green" : "label--gray";
                        }
                        @if (Model.ShowOffchainLabel)
                        {

                            <div class="confirmation_label label_group">
                                <span href="" class="label @confirmationsClass label--muted">@Model.OffchainLabel</span>
                                <span class="label @confirmationsClass">
                                    <i class="icon icon--check"></i>
                                    @(Model.Block?.Confirmations??0)
                                </span>
                            </div>
                        }
                        else
                        {
                            <div class="confirmation_label">
                                @if (Model.IsConfirmed)
                                {
                                    <span class="label @confirmationsClass">
                                        @(Model.Block?.Confirmations) Confirmations
                                    </span>
                                }
                                else
                                {
                                    <span class="label label--red label--plate">Unconfirmed</span>
                                }
                            </div>
                        }

                    </div>
                    <div class="col-sm-9">
                        <div class="address_code">
                            <a href="@Url.Action("Index", "Transaction", new {id = Model.TransactionId})">@Model.TransactionId</a>
                            <button class="btn btn--icon copy_code" type="button" title="Copy code">
                                <i class="icon icon--copy"></i>
                            </button>
                        </div>
                        @if (Model.Block != null)
                        {
                            <span class="action_text">@Model.Block.Time.ToStringBcnExplolerFormat()</span>
                            <span class="middot">·</span>
                        }
                        <span class="action_text">@Model.InputsCount @Utils.GenderAmount(Model.InputsCount, "input", "inputs", "inputs")</span>
                        
                        <span class="middot">·</span>
                        <span class="action_text">@Model.OutputsCount @Utils.GenderAmount(Model.OutputsCount, "output", "outputs", "outputs")</span>
                        
                        @if (Model.ShowChangeBtn)
                        {                        
                            <span class="middot">·</span>
                            <a href="#" class="action_text js-toggle-change-btn" data-toggle-container=".@toggleChangeContainer">
                                <span class="js-toggle-change-label">Show</span>
                                <span class="hidden js-toggle-change-label">Hide</span>
                                change
                            </a>
                        }
                    </div>
                </div>
            </div>
            <div class="panel__body">

                <div class="transaction_details">
                    <div class="transaction_details__header">
                        <table class="issuer">
                            <tbody>
                            <tr>
                                <td class="issuer__img"><img src="/img/assets/bitcoin.png" width="48" alt=""></td>
                                <td class="issuer__content">
                                    <div class="issuer__name pull-left">Bitcoin</div>
                                    <div class="wallet_value pull-right">
                                        <span class="@(Model.Bitcoin.ShowWithoutChange ? toggleChangeItemClass : "")">
                                            @Model.Bitcoin.Total.ToStringBtcFormat() BTC
                                        </span>
                                        @if (Model.Bitcoin.ShowWithoutChange)
                                        {
                                            <span class="@toggleChangeItemClass hidden">
                                                @Model.Bitcoin.TotalWithoutChange.ToStringBtcFormat() BTC
                                            </span>
                                        }
                                    </div>
 

                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="@(Model.Bitcoin.ShowWithoutChange ? toggleChangeItemClass : "")">
                        
                        @await Html.PartialAsync("~/Views/Shared/TransactionDetails/BtcInOuts.cshtml", BtcInOutsViewModel.CreateWithChange(Model.Bitcoin, showConsumedReleased: true))
                    </div>
                    @if (Model.Bitcoin.ShowWithoutChange)
                    {
                        <div class="@toggleChangeItemClass hidden">
                            @await Html.PartialAsync("~/Views/Shared/TransactionDetails/BtcInOuts.cshtml", BtcInOutsViewModel.CreateWithoutChange(Model.Bitcoin, showConsumedReleased: true))
                        </div>
                    }
                </div>

                @foreach (var coloredAsset in Model.ColoredAssets)
                {
                    var assetUrl = coloredAsset.IsKnown ? Url.Action("Index", "Asset", new {id= coloredAsset.AssetId}) : null;
                    <div class="transaction_details">
                        <div class="transaction_details__header">
                            <table class="issuer">
                                <tbody>
                                <tr>
                                    <td class="issuer__img">
                                        <a href="@assetUrl">
                                            <img src="@(!string.IsNullOrEmpty(coloredAsset.IconImageUrl) ? coloredAsset.IconImageUrl: "/img/be/asset_default.jpg")" width="48" alt="">
                                        </a>
                                    </td>
                                    <td class="issuer__content">

                                        <div class="issuer__name pull-left">
                                            <a href="@assetUrl">@coloredAsset.Name</a>
                                        </div>
                                        <div class="wallet_value pull-right">
                                            <span class = "@(coloredAsset.ShowWithoutChange? toggleChangeItemClass : "")">
                                                @coloredAsset.Total.ToStringBtcFormat() @coloredAsset.ShortName
                                            </span>
                                            @if (coloredAsset.ShowWithoutChange)
                                            {
                                                <span class="@toggleChangeItemClass hidden">
                                                    @coloredAsset.TotalWithoutChange.ToStringBtcFormat() @coloredAsset.ShortName
                                                </span>
                                            }
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    
                        <div class="@(coloredAsset.ShowWithoutChange ? toggleChangeItemClass : "")">
                            @await Html.PartialAsync("~/Views/Shared/TransactionDetails/ColoredInOuts.cshtml", ColoredAssetInOutsViewModel.CreateWithChange(coloredAsset))
                        </div>
                        @if (coloredAsset.ShowWithoutChange)
                        {
                            <div class="@toggleChangeItemClass hidden">
                                @await Html.PartialAsync("~/Views/Shared/TransactionDetails/ColoredInOuts.cshtml", ColoredAssetInOutsViewModel.CreateWithoutChange(coloredAsset))
                            </div>
                        }
                    </div>
                }

            </div>

        </div>
    </div>
}